### ISSUE TITLE
Backspace button needed!

### ISSUE THREAD

**Issue by SavFil** [teamTexnologiasLogismikou/CalculatorTest#2]
'Ενα button που θα αφαιρεί ένα ψηφίο την φορά από την οθόνη.

**Comment by stellaTer** [comment]
Αν δεν το θέλει κάποιος μπορώ να το πάρω?

**Comment by SavFil** [comment]
Είναι λιγο δίκοπο μαχαίρι, γιατί απο την μια κάποιος μπορεί να το θέλει, απο την άλλη να μην δει άμεσα το μήνυμα για να το πάρει...! Αν δεν σας πειράζει (_ΜΟΝΟ_ για το κομπιουτεράκι ας το δούμε σαν προσαρμογή), να βάλουμε ένα deadline μέχρι αύριο το απόγευμα και αν δεν το δει κάποιος/α αυτο το μηνυμα που κατα προτίμηση να μην έχει κάνει αλλο commit Πάρτο. .
